Repository Vitaljaz/hacktoberfest, pull requests merged in 2021-10, with the labels that each got.

#7 Prints Hello World in console
  2021/JavaScript/BestPractice/HelloWorld.js
Labels: hacktoberfest

#16 ft: Hello World in swift
  2021/Swift/BestPractice/HelloWorld.swift
Labels: hacktoberfest

#18 Fix : Hacktoberfest link
  README.md
Labels: bug, documentation, hacktoberfest

#27 Added swap_function for C++
  2021/C-Plus-Plus/BestPractice/swap_function.cpp
Labels: feature, hacktoberfest, c++

#28 Add sum_all function
  2021/C-Plus-Plus/BestPractice/sum_all_function.cpp
Labels: feature, hacktoberfest, c++

#26 ADD Bash folder and README.md
  2021/Bash/BestPractice/README.md
  2021/Bash/README.md
  2021/Bash/Scripts/README.md
Labels: documentation, enhancement, good first issue, feature, hacktoberfest

#30 Add scoped_ptr implementation
  2021/C-Plus-Plus/DataStructures/scoped_ptr.cpp
Labels: good first issue, hacktoberfest, c++

#15 Create Hello_world.c
  2021/C/BestPractice/Hello_world.c
Labels: hacktoberfest

#42 Add argparse for python
  2021/Python/BestPractice/argparse.py
Labels: enhancement, good first issue, feature, hacktoberfest

#22 add Hello World to Kotlin
  2021/Kotlin/BestPractice/HelloWorld.kt
Labels: enhancement, good first issue, feature, hacktoberfest

#23 hello world program in go
  2021/Go/BestPractice/hello_world.go
Labels: good first issue, feature, hacktoberfest

#25 Hello World in scala
  2021/Scala/Algorithms/HelloWorld.scala
  2021/Scala/Algorithms/README.md
Labels: good first issue, feature, hacktoberfest

#29 Added Hello World in Dart
  2021/Dart/Algorithms/README.md
  2021/Dart/BestPractice/HelloWorld.dart
  2021/Dart/BestPractice/README.md
  2021/Dart/DataStructures/README.md
  2021/Dart/README.md
Labels: good first issue, feature, hacktoberfest

#31 Add HelloWorld in Ruby
  2021/Ruby/BestPractice/helloworld.rb
Labels: hacktoberfest

#32 Adding Helloworld.java
  2021/Java/BestPractice/Helloworld.java
Labels: feature, hacktoberfest

#43 Python: For loop for 10 iterations
  2021/Python/BestPractice/for_loop.py
Labels: enhancement, good first issue, feature, hacktoberfest

#41 Added Kadane's Algorithm
  2021/Python/Algorithms/kadane.py
Labels: good first issue, feature, hacktoberfest

#44 Added New Sorting Algorithm
  2021/Python/Algorithms/Bubble_sort.py
Labels: enhancement, good first issue, feature, hacktoberfest

#46 Added SHA-1 hashing algorithm.
  2021/C-Plus-Plus/Algorithms/SHA-1.cpp
Labels: enhancement, good first issue, feature, hacktoberfest, c++

#2 Created a cpp file in Bestpractice folder.
  2021/C-Plus-Plus/BestPractice/hello_world.cpp
  2021/C-Plus-Plus/BestPractice/hello_world.exe
Labels: hacktoberfest

#57 Added Iterative implementation of selection sort.
  2021/C-Plus-Plus/Sorting/selection_sort_iterative.cpp
Labels: good first issue, feature, hacktoberfest, hacktoberfest-accepted

#56 Added factorial implementation in go
  2021/Go/Algorithms/factorial.go
Labels: good first issue, feature, hacktoberfest, hacktoberfest-accepted

#50 Add Python staircase program
  2021/Python/Algorithms/staircase.py
Labels: enhancement, good first issue, feature, hacktoberfest, hacktoberfest-accepted

#51 Added fibonacci no upto n
  2021/Java/BestPractice/fibonacci_series.java
Labels: enhancement, good first issue, feature, hacktoberfest, hacktoberfest-accepted

#52 Added Minimum Jumps to the End of the Array
  2021/Python/Algorithms/Mini_no_of_jumps.py
Labels: enhancement, good first issue, feature, hacktoberfest, hacktoberfest-accepted

#53 Added a chatbot project
  2021/Python/Algorithms/Quick_sort.py
  2021/Python/BestPractice/calculator.py
  2021/Python/Python Projects/Chatbot/chatbot.gui
  2021/Python/Python Projects/Chatbot/chatbot.py
  2021/Python/Python Projects/Chatbot/intents.json
  2021/Python/Python Projects/Chatbot/test_strint.py
  2021/Python/Python Projects/Chatbot/train_chatbot.py
Labels: enhancement, good first issue, feature, hacktoberfest, hacktoberfest-accepted

#54 preorder-traversal of binary tree added
  2021/C-Plus-Plus/Algorithms/preorder.cpp
Labels: good first issue, feature, hacktoberfest, hacktoberfest-accepted

#55 Create helloworld.cs
  2021/C-Sharp/BestPractice/helloworld.cs
Labels: enhancement, good first issue, feature, hacktoberfest, hacktoberfest-accepted

#59 Added reverse linked list algorithm.
  2021/C-Plus-Plus/DataStructures/reverse_a_linked_list.cpp
Labels: enhancement, good first issue, feature, hacktoberfest, hacktoberfest-accepted

#60 add factorial program for javascript
  2021/JavaScript/Algorithms/factorial.js
Labels: enhancement, good first issue, feature, hacktoberfest, hacktoberfest-accepted

#61 added forLoopTill10.cpp
  2021/C-Plus-Plus/Algorithms/forLoopTill10.cpp
Labels: good first issue, feature, hacktoberfest, hacktoberfest-accepted

#62 added factorial.cpp
  2021/C-Plus-Plus/Algorithms/factorial.cpp
Labels: enhancement, good first issue, feature, hacktoberfest, hacktoberfest-accepted

#49 implementation of factorial function.c
  2021/C/Algorithms/Staircase function.c
Labels: good first issue, feature, hacktoberfest, hacktoberfest-accepted

#64 added staircase.js
  2021/JavaScript/Algorithms/staircase.js
Labels: enhancement, good first issue, feature, hacktoberfest, hacktoberfest-accepted

#67 Create hello-world.sh
  2021/Bash/BestPractice/hello-world.sh
Labels: good first issue, feature, hacktoberfest, hacktoberfest-accepted

#68 Added printStaircase in JavaScript
  2021/JavaScript/Algorithms/staircase_tchestnut85.js
Labels: good first issue, feature, hacktoberfest, hacktoberfest-accepted

#96 Adding Insertion , Merge and Selection Sorting
  2021/Python/Algorithms/ArraySum.py
  2021/Python/Algorithms/InsertionSort.py
  2021/Python/Algorithms/MergeSort.py
  2021/Python/Algorithms/SelectionSort.py
Labels: good first issue, feature, hacktoberfest, hacktoberfest-accepted

#95 added array sum function for c++
  2021/C-Plus-Plus/Algorithms/array_sum.cpp
Labels: enhancement, good first issue, feature, hacktoberfest, hacktoberfest-accepted

#94 added quick sort algorithm
  2021/Python/Algorithms/quick_sort.py
Labels: good first issue, feature, hacktoberfest, hacktoberfest-accepted

#92 Add Simple Array Sum for Python
  2021/Python/Algorithms/simple_array_sum.py
Labels: enhancement, good first issue, feature, hacktoberfest, hacktoberfest-accepted

#91 this is a simple chat bot code
  2021/Python/simplechatbot.py
Labels: enhancement, good first issue, feature, hacktoberfest, hacktoberfest-accepted

#90 tic_tac_toe program
  2021/C-Plus-Plus/Algorithms/SHA-1.cpp
  2021/C-Plus-Plus/BestPractice/hello_world.cpp
  2021/C-Plus-Plus/BestPractice/hello_world.exe
  2021/C-Plus-Plus/Sorting/selection_sort_iterative.cpp
  2021/C/Algorithms/heap_sort.c
  2021/Dart/Algorithms/README.md
  2021/Dart/BestPractice/HelloWorld.dart
  2021/Dart/BestPractice/README.md
  2021/Dart/DataStructures/README.md
  2021/Dart/README.md
  2021/Go/Algorithms/factorial.go
  2021/Go/BestPractice/hello_world.go
  2021/Java/BestPractice/Helloworld.java
  2021/Kotlin/BestPractice/HelloWorld.kt
  2021/Python/Algorithms/Bubble_sort.py
  2021/Python/Algorithms/factorial.py
  2021/Python/Algorithms/kadane.py
  2021/Python/BestPractice/for_loop.py
  2021/Python/password_generator.py
  2021/Python/tic_tac_toe.py
  2021/Ruby/BestPractice/helloworld.rb
  2021/Scala/Algorithms/HelloWorld.scala
  2021/Scala/Algorithms/README.md
  Untitled-1.cpp
Labels: enhancement, good first issue, feature, hacktoberfest, hacktoberfest-accepted

#99 Argparse python
  2021/C/Algorithms/heap_sort.c
  2021/Python/password_generator.py
  2021/Python/tic_tac_toe.py
  Untitled-1.cpp
Labels: good first issue, feature, hacktoberfest, hacktoberfest-accepted

#80 added linked_list.py file
  2021/C-Plus-Plus/Algorithms/SHA-1.cpp
  2021/C-Plus-Plus/Algorithms/linearSearch.cpp
  2021/C-Plus-Plus/Algorithms/linear_search.cpp
  2021/C-Plus-Plus/BestPractice/hello_world.cpp
  2021/C-Plus-Plus/BestPractice/hello_world.exe
  2021/C-Plus-Plus/Sorting/selection_sort_iterative.cpp
  2021/C/BestPractice/Hello_world.c
  2021/Dart/Algorithms/README.md
  2021/Dart/BestPractice/HelloWorld.dart
  2021/Dart/BestPractice/README.md
  2021/Dart/DataStructures/README.md
  2021/Dart/README.md
  2021/Go/Algorithms/factorial.go
  2021/Go/BestPractice/hello_world.go
  2021/Java/BestPractice/Helloworld.java
  2021/JavaScript/Algorithms/linear_search.js
  2021/Kotlin/BestPractice/HelloWorld.kt
  2021/Python/Algorithms/Bubble_sort.py
  2021/Python/Algorithms/factorial.py
  2021/Python/Algorithms/heap_algorithm.py
  2021/Python/Algorithms/kadane.py
  2021/Python/Algorithms/merge_sort.py
  2021/Python/Algorithms/power.py
  2021/Python/BestPractice/argparse.py
  2021/Python/BestPractice/for_loop.py
  2021/Python/DataStructures/linked_list.py
  2021/Python/NLP/chat_bot.py
  2021/Ruby/BestPractice/helloworld.rb
  2021/Scala/Algorithms/HelloWorld.scala
  2021/Scala/Algorithms/README.md
Labels: enhancement, good first issue, feature, hacktoberfest, hacktoberfest-accepted

#74 added merge_sort.py
  2021/C-Plus-Plus/Algorithms/linearSearch.cpp
  2021/C-Plus-Plus/Algorithms/linear_search.cpp
  2021/JavaScript/Algorithms/linear_search.js
  2021/Python/Algorithms/heap_algorithm.py
  2021/Python/Algorithms/merge_sort.py
  2021/Python/Algorithms/power.py
  2021/Python/DataStructures/linked_list.py
  2021/Python/NLP/chat_bot.py
Labels: good first issue, feature, hacktoberfest, hacktoberfest-accepted

#72 Create insertion_sort.cpp
  2021/C-Plus-Plus/Sorting/insertion_sort.cpp
Labels: enhancement, good first issue, feature, hacktoberfest, hacktoberfest-accepted

#103 Fix problems in repo
  Untitled-1.cpp
Labels: enhancement, good first issue, feature, hacktoberfest, hacktoberfest-accepted

#104 [Python] Add best practice with using zip
  2021/Python/Algorithms/Quick_sort.py
  2021/Python/Algorithms/quick_sort.py
  2021/Python/BestPractice/zip.py
Labels: enhancement, good first issue, feature, hacktoberfest, hacktoberfest-accepted

#105 [Python] Add best practice with using enumerate
  2021/Python/BestPractice/enumerate.py
Labels: enhancement, good first issue, feature, hacktoberfest, hacktoberfest-accepted

#106 [Python] Add best practice with using list comprehensions
  2021/Python/BestPractice/list_comprehensions.py
Labels: enhancement, good first issue, feature, hacktoberfest, hacktoberfest-accepted

#140 Adding staircase function
  2021/JavaScript/Algorithms/staircase_fun.js
Labels: enhancement, feature, hacktoberfest, hacktoberfest-accepted

#119 add linear search bash script
  2021/Bash/Scripts/LinearSearch.sh
Labels: enhancement, feature, hacktoberfest, hacktoberfest-accepted

#117 Added Java Example
  2021/Java/BestPractice/Calculate Random License Plate Number.java
Labels: good first issue, feature, hacktoberfest, hacktoberfest-accepted

#133 Create GeneratingBill.cs
  2021/C-Sharp/BestPractice/GeneratingBill.cs
Labels: good first issue, feature, hacktoberfest, hacktoberfest-accepted

#131 Implemented stack data structure in C programming
  2021/C/DataStructures/stack.c
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#138 add bash script
  2021/Bash/Scripts/looping-one-line.sh
Labels: enhancement, good first issue, feature, hacktoberfest, hacktoberfest-accepted

#189 Creates Simple array sum.py
  Simple array sum.py
Labels: enhancement, good first issue, feature, hacktoberfest, hacktoberfest-accepted

#182 Add *Reversing array using 'reverse()' function present in library -> Algorithm in c++*
  2021/C-Plus-Plus/Algorithms/a.out
  2021/C-Plus-Plus/Algorithms/reverse_array.cpp
Labels: enhancement, good first issue, feature, hacktoberfest, hacktoberfest-accepted

#183 Add a gui chat app shell with no networking as it can be done by other users!
  2021/Java/GUI Chat Shell/BasicChatAppInterface.class
  2021/Java/GUI Chat Shell/BasicChatAppInterface.java
Labels: enhancement, good first issue, feature, hacktoberfest, hacktoberfest-accepted

#181 Insertion at end of a singly linked list
  2021/C-Plus-Plus/DataStructures/insertion_at_end_singly_linked_list.cpp
Labels: enhancement, good first issue, feature, hacktoberfest, hacktoberfest-accepted

#180 feat: sum array of numbers
  2021/JavaScript/Algorithms/sum_array.js
Labels: enhancement, good first issue, feature, hacktoberfest, hacktoberfest-accepted

#179 Add: Quick Sort in C
  2021/C/DataStructures/quick_sort.c
Labels: enhancement, good first issue, feature, hacktoberfest, hacktoberfest-accepted

#177 Added Spam detection via bert
  2021/Python/NLP/bert_spam_detection.py
Labels: enhancement, good first issue, feature, hacktoberfest, hacktoberfest-accepted

#176 feat(linked_list.py): Update Node and UnorderedLinkedList classes
  .gitignore
  2021/Python/DataStructures/linked_list.py
Labels: enhancement, good first issue, feature, hacktoberfest, hacktoberfest-accepted

#174 Staircase code in c++.
  2021/C-Plus-Plus/Algorithms/staicase.c++
  2021/Python/README.md
Labels: enhancement, good first issue, feature, hacktoberfest, hacktoberfest-accepted

#171 Add optimized bubble sort algorithm
  2021/C/Algorithms/insertion_sort.c
  2021/C/Algorithms/optimized_bubble_sort.c
Labels: enhancement, good first issue, feature, hacktoberfest, hacktoberfest-accepted

#168 Create print.py
  2021/JavaScript/print.py
Labels: enhancement, good first issue, feature, hacktoberfest, hacktoberfest-accepted

#167 added binary search algorithm
  2021/C-Plus-Plus/Algorithms/binary_search.cpp
Labels: enhancement, good first issue, feature, hacktoberfest, hacktoberfest-accepted

#166 Added the Height of the Program
  2021/C-Plus-Plus/Algorithms/Height_Of_Tree.cpp
Labels: enhancement, good first issue, feature, hacktoberfest, hacktoberfest-accepted

#164 Create memorygame.py
  2021/Python/memorygame.py
Labels: enhancement, good first issue, feature, hacktoberfest, hacktoberfest-accepted

#163 Added calculator and armstrong number detector
  2021/Python/armstrong number.py
  2021/Python/calculator.py
Labels: enhancement, good first issue, feature, hacktoberfest, hacktoberfest-accepted

#154 Path sum of Binary tree
  2021/C-Plus-Plus/DataStructures/pathSumOfBinaryTree.cpp
Labels: enhancement, good first issue, feature, hacktoberfest, hacktoberfest-accepted

#150 fix issues, simplify expressions
  2021/Python/Algorithms/ArraySum.py
  2021/Python/Algorithms/factorial.py
  2021/Python/Algorithms/kadane.py
  2021/Python/BestPractice/argparse.py
  2021/Python/BestPractice/calculator.py
  2021/Python/BestPractice/list_comprehensions.py
Labels: enhancement, good first issue, feature, hacktoberfest, hacktoberfest-accepted

#147 Tree with inorder and post order array and some traversals
  2021/C-Plus-Plus/DataStructures/Tree And Some Functions.cpp
Labels: enhancement, good first issue, feature, hacktoberfest, hacktoberfest-accepted

#146 Create stonepaperscissor.py
  2021/Python/stonepaperscissor.py
Labels: enhancement, good first issue, feature, hacktoberfest, hacktoberfest-accepted

#145 Add Bfs Algorithm Code
  2021/C-Plus-Plus/Algorithms/bfs.cpp
Labels: enhancement, good first issue, feature, hacktoberfest, hacktoberfest-accepted

#144 Collect the balls.java
  2021/Java/BestPractice/Collect the balls.java
Labels: enhancement, good first issue, feature, hacktoberfest, hacktoberfest-accepted

#141 Add BubleSort Algorithm java
  2021/Java/Algorithms/BubleSort.java
Labels: enhancement, good first issue, feature, hacktoberfest, hacktoberfest-accepted
